################################################################################
############################ Variables to change ###############################
##### Sources directory
SRC_DIR		= src

##### Main file, without .tex extension.
NAME		= rapport-stage

INCLUDED_TEX_FILES = conclusion extra_erasmus presentation tasks

##### Output directory
# If not modified, it is the directory which holds the MakeFile
OUTPUT_DIR	= _build

##### Executable/output to use: PDFLATEX, DVILUATEX
CC			= $(PDFLATEX)
CC_BIB		= $(BIBTEX)
USE_BIB		= true
################################################################################
